### ISSUE TITLE
container for ngs-qc generator

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/Dockers#11]
The old chip-seq workflow points to `/data/CCBR_Pipeliner/db/PipeDB/ChIPseq/NGSQC_linux_x86_64` as the binary file to run ngs-qc. The tool's online docs point to a galaxy portal, and it's not clear to me how this was / could be installed as a CLI.

**Comment by kopardev** [comment]
@kelly-sovacool 
Use docker "nciccbr/ccbr_ngsqc_0.31:v1"
both `ngsqc` and `NGSQC_linux_x86_64` have been added to `PATH`
