### ISSUE TITLE
Install phantompeakqualtools instead of copying scripts?

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/Dockers#5]
Is there a better way to support phantompeakqualtools than have the scripts copied in the container (<https://github.com/CCBR/Dockers/tree/14c7a3a84c0bdd81ad207d7724a57a61013f6f56/chipseq/ccbr_spp_1.14>)? It is available on bioconda: <https://bioconda.github.io/recipes/phantompeakqualtools/README.html#package-phantompeakqualtools>, perhaps the docker could install it mamba.

**Comment by kelly-sovacool** [comment]
There's actually a docker container available used by the nf-core chip-seq pipeline. We could just use that instead of duplicating our efforts. https://github.com/nf-core/chipseq/blob/51eba00b32885c4d0bec60db3cb0a45eb61e34c5/modules/nf-core/modules/phantompeakqualtools/main.nf

**Comment by kopardev** [comment]
@kelly-sovacool, Sure go ahead and use the biocontainers docker ... but make sure to isolate the process as `/opt2` `/data2 will not be available and other tools may be different from the versions in `ccbr_base`... Ok?
